# Generated by Django 2.2.24 on 2025-04-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flatadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatAdmin',
        ),
    ]
