# Generated by Django 5.2 on 2025-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20250422_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_flats',
            field=models.ManyToManyField(related_name='owners_flats', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
