# Generated by Django 5.2 on 2025-04-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_owner_owners_flats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_number',
        ),
    ]
