# Generated by Django 5.2 on 2025-04-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20250424_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_flats',
            field=models.ManyToManyField(db_index=True, related_name='owners_flats', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер владельца'),
        ),
    ]
