# Generated by Django 5.2 on 2025-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_owner_owners_flats_alter_owner_owners_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_flats',
            field=models.ManyToManyField(db_index=True, related_name='owned_by', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
